export const TERMS_OF_SERVICE = `TERMS OF SERVICE

Last Updated: February 28, 2026

Welcome to Zynthr, operated by [COMPANY_NAME]. By creating an account or using our platform, you agree to these Terms of Service ("Terms"). Please read them carefully.

1. SERVICE DESCRIPTION

Zynthr is an AI-powered command center platform that provides intelligent automation, workflow management, role-based access control (RKBAC), and operational intelligence for organizations. The Platform includes AI agents, bots, chat interfaces, ticketing systems, training modules, and integrations with third-party services.

The Platform is provided on a software-as-a-service (SaaS) basis. [COMPANY_NAME] hosts, maintains, and updates the Platform. Your access is subject to your subscription plan and these Terms.

2. USER ACCOUNTS

2.1 Registration. You must provide accurate, complete, and current information when creating an account. You are responsible for maintaining the confidentiality of your login credentials.

2.2 Account Security. You must immediately notify [COMPANY_NAME] of any unauthorized use of your account. You are responsible for all activity under your account.

2.3 Organization Accounts. If you create an account on behalf of an organization, you represent that you have authority to bind that organization to these Terms. The organization is the "Customer" and is responsible for all users within its tenant.

2.4 Age Requirement. You must be at least 18 years old to use the Platform.

3. ACCEPTABLE USE

You agree not to:

(a) Use the Platform for any unlawful purpose or in violation of any applicable laws or regulations;
(b) Attempt to gain unauthorized access to any part of the Platform, other accounts, or connected systems;
(c) Introduce malicious code, viruses, or harmful data into the Platform;
(d) Use the Platform to transmit spam, phishing attempts, or unsolicited communications;
(e) Reverse engineer, decompile, or disassemble any part of the Platform;
(f) Use AI agents or bots to generate content that is fraudulent, defamatory, or harmful;
(g) Attempt to circumvent RKBAC policies, permission tiers, or security controls;
(h) Share login credentials or allow unauthorized persons to access your account;
(i) Use the Platform in a way that could damage, disable, or impair the service for others;
(j) Scrape, harvest, or collect data from the Platform without authorization.

4. INTELLECTUAL PROPERTY

4.1 Platform Ownership. The Platform, including all software, algorithms, AI models, user interfaces, documentation, and trademarks, is owned by [COMPANY_NAME] and protected by intellectual property laws. Nothing in these Terms grants you ownership of the Platform.

4.2 Your Content. You retain ownership of all data, documents, and content you upload to or create within the Platform ("Your Content"). By using the Platform, you grant [COMPANY_NAME] a limited license to process Your Content solely to provide the services.

4.3 AI-Generated Content. Content generated by AI agents and bots within the Platform is provided for your use. You are responsible for reviewing and validating AI-generated content before relying on it for business decisions.

4.4 Feedback. If you provide suggestions, feedback, or ideas about the Platform, [COMPANY_NAME] may use them without obligation to you.

5. DATA OWNERSHIP

5.1 Your Data. All data you input, upload, or generate through the Platform remains your property. [COMPANY_NAME] does not claim ownership of Your Content.

5.2 Data Processing. [COMPANY_NAME] processes your data solely to provide and improve the Platform services. We do not sell your data to third parties.

5.3 Data Portability. You may export your data at any time through the Platform export features or by contacting support.

5.4 Data Isolation. Each organization data is logically isolated within the Platform through multi-tenant architecture. No other tenant can access your data.

5.5 AI Training. Your data will not be used to train AI models without your explicit written consent.

6. WARRANTIES AND DISCLAIMERS

6.1 Service Availability. [COMPANY_NAME] will use commercially reasonable efforts to maintain Platform availability but does not guarantee uninterrupted access.

6.2 AI Accuracy. AI-generated content, recommendations, and analyses are provided as-is and may contain errors. You are responsible for verifying AI outputs before acting on them.

6.3 DISCLAIMER. TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE PLATFORM IS PROVIDED AS IS AND AS AVAILABLE WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.

6.4 No Professional Advice. The Platform does not provide legal, medical, financial, or other professional advice. Consult qualified professionals for such matters.

7. LIMITATION OF LIABILITY

7.1 TO THE MAXIMUM EXTENT PERMITTED BY LAW, [COMPANY_NAME] SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.

7.2 [COMPANY_NAME] TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS OR THE PLATFORM SHALL NOT EXCEED THE AMOUNT YOU PAID TO [COMPANY_NAME] IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM.

7.3 These limitations apply regardless of the theory of liability (contract, tort, negligence, strict liability, or otherwise) and even if [COMPANY_NAME] has been advised of the possibility of such damages.

8. TERMINATION

8.1 By You. You may terminate your account at any time through the Platform settings or by contacting support. Upon termination, your access will cease and your data will be handled according to the Data Retention section of our Privacy Policy.

8.2 By [COMPANY_NAME]. [COMPANY_NAME] may suspend or terminate your access if you violate these Terms, fail to pay applicable fees, or if required by law. We will provide reasonable notice when possible.

8.3 Effect of Termination. Upon termination: (a) your license to use the Platform ends immediately; (b) you must cease all use of the Platform; (c) [COMPANY_NAME] will retain your data for 30 days to allow export, after which it may be deleted.

9. GOVERNING LAW

9.1 These Terms shall be governed by and construed in accordance with the laws of the State of Florida, without regard to its conflict of law provisions.

9.2 Any disputes arising from these Terms shall be resolved exclusively in the state or federal courts located in Duval County, Florida.

9.3 You agree to waive any right to a jury trial in connection with any dispute arising under these Terms.

10. GENERAL PROVISIONS

10.1 Entire Agreement. These Terms, together with the Privacy Policy and any applicable Business Associate Agreement, constitute the entire agreement between you and [COMPANY_NAME].

10.2 Modifications. [COMPANY_NAME] may update these Terms from time to time. We will notify you of material changes. Continued use after changes constitutes acceptance.

10.3 Severability. If any provision of these Terms is found unenforceable, the remaining provisions will continue in effect.

10.4 Assignment. You may not assign your rights under these Terms without [COMPANY_NAME] written consent.

10.5 Contact. For questions about these Terms, contact us at legal@zynthr.com.`


export const PRIVACY_POLICY = `PRIVACY POLICY

Last Updated: February 28, 2026

[COMPANY_NAME] ("we," "us," or "our") operates the Zynthr platform. This Privacy Policy describes how we collect, use, store, and protect your information when you use our services.

1. INFORMATION WE COLLECT

1.1 Account Information. When you create an account, we collect your name, email address, organization name, and password. If you sign up through SSO (Microsoft Entra ID or Google), we receive your profile information from the identity provider.

1.2 Organization Data. Information about your organization including industry, size, department structure, team members, and role assignments.

1.3 Usage Data. We collect information about how you use the Platform, including pages visited, features used, AI queries made, workflows created, and interaction patterns.

1.4 Device and Technical Data. Browser type, operating system, IP address, device identifiers, and session information.

1.5 Content Data. All data, documents, messages, and content you upload to or create within the Platform, including AI chat conversations and generated outputs.

1.6 Integration Data. When you connect third-party services (Microsoft 365, Google Workspace, Slack, etc.), we access data as authorized by your integration permissions.

1.7 Communication Data. Records of support requests, feedback, and communications with our team.

2. HOW WE USE YOUR INFORMATION

2.1 Provide Services. To operate, maintain, and deliver the Platform features you use.

2.2 Personalization. To customize the Platform experience based on your organization industry, preferences, and usage patterns.

2.3 AI Processing. To power AI agents, bots, and intelligent features within the Platform. AI interactions are processed to generate responses, recommendations, and automations.

2.4 Security. To detect, prevent, and respond to security threats, fraud, and abuse. This includes audit logging, anomaly detection, and access monitoring.

2.5 Communications. To send transactional emails (account verification, password resets, billing), platform updates, and, with your consent, marketing communications.

2.6 Improvement. To analyze usage patterns and improve the Platform features, performance, and reliability.

2.7 Legal Compliance. To comply with applicable laws, regulations, legal processes, or government requests.

3. DATA STORAGE AND SECURITY

3.1 Encryption. All data is encrypted at rest using AES-256 encryption and in transit using TLS 1.3.

3.2 Multi-Tenant Isolation. Each organization data is logically isolated. Row-level security policies ensure no cross-tenant data access.

3.3 Access Controls. We implement role-based access controls (RKBAC) limiting data access to authorized personnel and systems only.

3.4 Audit Logging. All access to sensitive data is logged for audit and compliance purposes.

3.5 Infrastructure. Data is hosted on secure cloud infrastructure with SOC 2 Type II certified providers. Primary data storage is in the United States.

3.6 Backups. Regular encrypted backups are maintained for disaster recovery purposes.

3.7 Session Security. Automatic session timeout after 15 minutes of inactivity. Single-session enforcement available per organization policy.

4. THIRD-PARTY SERVICES

4.1 We use the following categories of third-party service providers:

- Cloud Infrastructure: For hosting and data storage
- AI Model Providers: For powering AI features (Anthropic, OpenAI)
- Payment Processing: Stripe for subscription billing
- Analytics: For Platform usage analytics
- Email: For transactional and communication emails

4.2 Each third-party provider is bound by data processing agreements that require them to protect your data and use it only for the specified purposes.

4.3 AI Model Providers. We contractually require that AI model providers do not retain, train on, or use your data beyond the immediate processing request.

4.4 We do not sell your personal information to third parties.

5. YOUR RIGHTS

5.1 Access. You may request a copy of the personal information we hold about you.

5.2 Correction. You may update or correct your personal information through your account settings or by contacting us.

5.3 Deletion. You may request deletion of your personal information, subject to legal retention requirements.

5.4 Data Portability. You may export your data in standard formats through the Platform or by contacting support.

5.5 Opt-Out. You may opt out of marketing communications at any time. You may disable non-essential cookies through your browser settings.

5.6 Restriction. You may request that we restrict processing of your personal information in certain circumstances.

5.7 To exercise any of these rights, contact us at privacy@zynthr.com.

6. HIPAA COMPLIANCE (FOR HEALTHCARE CLIENTS)

6.1 If your organization is a Covered Entity under HIPAA, we will enter into a Business Associate Agreement (BAA) with you prior to processing any Protected Health Information (PHI).

6.2 PHI Handling. When a BAA is in place:
- PHI is encrypted at rest and in transit
- Access to PHI is restricted to authorized users based on RKBAC policies
- All PHI access is logged for audit purposes
- PHI is not used for AI model training
- AI model providers are contractually prohibited from retaining PHI
- De-identification of PHI requires explicit written authorization

6.3 Breach Notification. In the event of a breach involving PHI, we will notify the Covered Entity within 30 calendar days of discovery, as required by HIPAA and the HITECH Act.

6.4 Minimum Necessary. We access, use, and disclose only the minimum amount of PHI necessary to provide the Platform services.

7. DATA RETENTION

7.1 Account Data. We retain your account information for as long as your account is active and for 30 days after termination to allow data export.

7.2 Usage Data. Aggregated and anonymized usage data may be retained indefinitely for analytical purposes.

7.3 Audit Logs. Audit logs are retained according to your organization configured retention period (default: 90 days, configurable up to indefinite).

7.4 Chat History. AI chat conversations are retained according to your organization configured retention period (default: 30 days).

7.5 Backups. Backup data is retained for 90 days and then securely destroyed.

7.6 Legal Requirements. We may retain data longer if required by applicable law or legal proceedings.

8. CHANGES TO THIS POLICY

8.1 We may update this Privacy Policy from time to time. We will notify you of material changes by email or through the Platform.

8.2 The "Last Updated" date at the top of this policy indicates when the latest revision was made.

8.3 Your continued use of the Platform after changes constitutes acceptance of the updated policy.

9. CONTACT

For questions, concerns, or requests regarding this Privacy Policy or your data:

Email: privacy@zynthr.com
Address: [COMPANY_NAME], Jacksonville, Florida

For HIPAA-related inquiries: hipaa@zynthr.com

Data Protection Officer: dpo@zynthr.com`
